---
title: "6451IP-Week-4-Problem-Set2 | MULTIPLE LINEAR REGRESSION, Part 3 Problem Set #2"
author: "Patrick Torralba"
date: "2026-02-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#library
```{r load library}
library(tidyverse)
library(car)
library(olsrr)
```

#import data
```{r load tomhs data from github}
url <- "https://raw.githubusercontent.com/torra034-svg/biostats/refs/heads/main/Biostats%202/Data%20Stuff/tomhs.csv"

tomhs <- read_csv(url)
```

```{r remove url}
rm(url)

```

#Questions

```{r q1 create variables}
tomhs <- tomhs %>% 
  mutate(wtchg = wt12 - wtbl,
         cholchg = chol12 - cholbl)
```

```{r q2 MLR model}

model_adjusted <- lm(data = tomhs, cholchg ~ wtchg + nowsmk)

summary(model_adjusted)
```


```{r q3 check for outliers via cooks model}

n <- nobs(model_adjusted) #define number of observations first in the model

which(cooks.distance(model_adjusted) > 4/n) #this line identifies outliers

```


```{r q4 check standardized residuals}

which(abs(rstandard(model_adjusted)) > 2) # make sure to only look at bottom row as the observation output. Ignore the top row.

```


```{r q5 check for strong standardized residuals}

which(abs(rstandard(model_adjusted)) > 3) # this checks for strong residuals

```


```{r q6 studentized residuals}

rstudent(model_adjusted) #studentized residuals tell us how many st.dev away an observed value is from the predicted value

```

Now I need to 

|         | Interpretation   |
| ------- | ---------------- |
| |r| < 2 | Normal           |
| |r| > 2 | Possible outlier |
| |r| > 3 | Likely outlier   |
| |r| > 4 | Strong outlier   |

```{r q7 studentized residuals of concern}

which(abs(rstudent(model_adjusted))>3) #again ignore the top row bc that is the character position. The true observation output is in the second row.

```


```{r q11 cooks distance}

cooks.distance(model_adjusted)

```


```{r q13 DFFITS plot}

ols_plot_dffits(model_adjusted)
```


```{r q14 DFFITS values of concern}

p <- length(coef(model_adjusted)) #number of parameters

threshold <- 2 * sqrt(p / n)

which(abs(dffits(model_adjusted)) > threshold )
```

```{r q15 DFBETAS}

DFBETAS <- dfbetas(model_adjusted)

dfbeta_flag <- which(abs(DFBETAS) > 1)

```


```{r q19 multicollinearity}

vif(model_adjusted)

```

