---
title: "collab key 2"
author: "Patrick Torralba"
date: "2026-02-04"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#library
```{r}
library(tidyverse)
library(summarytools)
```

#import data
```{r}
tomhs <- read.csv(file = "C:/Users/Lenovo/OneDrive/Documents/Biostats 2/Data Stuff/tomhs.csv", header = TRUE)
```


#Creating a Multi-Category

#1)
```{r data cleaning}
tomhs1 <- tomhs %>% 
  mutate(wtchg = wt12 - wtbl,
         cholchg = chol12 - cholbl)
```

```{r participant count}
descr(tomhs1$wtchg)

#There's a total of 848 patients with non-missing values.
```

#3
```{r}
tomhs1 <- tomhs1 %>% 
  mutate(wtchgcat = case_when(
    wtchg <= -10 ~ "lost10plus",
    wtchg <= 0 ~ "lost0to10",
    wtchg > 0 ~ "gained"
  ))

```

#4)
```{r}
ggplot(tomhs1, aes(x = wtchgcat, y = wtchg)) +
  geom_boxplot() +
  labs(x = "Weight Change Categories",
       y = "Weight Chabge (lb)",
       title = "Weight Change Distribution by Category")
```

#5) 
```{r}
wt_check <- tomhs1 %>% 
  select(wtchg, wtchgcat) %>% 
  group_by(wtchgcat) %>% 
  summarize(max = max(wtchg),
            min = min(wtchg))

wt_check
```

#6)
```{r}
wt_check_count <- tomhs1 %>% 
  group_by(wtchgcat) %>% 
  summarize(category_count = n())

wt_check_count
```

# Model 1

#7)
```{r}
ggplot(tomhs1, aes(x = wtchgcat, y = cholchg)) +
  geom_boxplot() +
  labs(x = "Weight Change",
       y = "Cholesterol Change",
       title = "Total Cholesterol Change by Weight Change Category")
```

#9) 

```{r relevel reference tidyverse}

tomhs1 <- tomhs1 %>% 
  mutate(wtchgcat = fct_relevel(wtchgcat, "lost10plus"))

```

```{r SLR}
model <- lm(tomhs1$cholchg ~ tomhs1$wtchgcat) 

summary(model)
```

#16) 

```{r load library}
library(car)
```

```{r ANOVA-F Test}

Anova(model, type ="III")

```

#19)
```{r}
ggplot(tomhs1, aes(y = cholchg, x = height, color = wtchgcat)) +
  geom_point()
```

#20
```{r reference category}
tomhs1 <- tomhs1 %>% 
  mutate(wtchgcat = fct_relevel(wtchgcat, "lost10plus"))
```

```{r MLR}
model1 <- lm(tomhs1$cholchg ~ tomhs1$wtchgcat + tomhs1$height)

summary(model1)
```


#25
```{r ANOVA F-test}
Anova(model1, type = "III")
```

