---
title: "Week 6: Homework - Logistic Regression"
author: "Patrick Torralba"
format: html
editor: visual
---

# Report

## Load and import data

```{r load library, include=FALSE, echo=FALSE}
library(tidyverse)
library(broom) #for aesthetic clean tables
library(flextable) # export tables
library(ResourceSelection) # for hosmer-lemeshow test
library(car) #for multicollinearity
library(gtsummary)
```

```{r import data, include=FALSE, echo=FALSE}
url <- "https://raw.githubusercontent.com/torra034-svg/biostats/refs/heads/main/Biostats%202/Data%20Stuff/dekaf_dgf.csv"

dekaf <- read.csv(url)
```

```{r remove url, echo=FALSE}

rm(url)

```

## Dataset Data Cleaning

```{r create Cardiac Death variable}

dekaf <- dekaf %>% 
  mutate(cardiac_death = if_else(dcd_yn == 1, "Yes", "No", missing = NULL),
         DGF = if_else(dgf == 1, "Yes", "No", missing = NULL))

```

## Exploratory Data Analysis

### Table 1: Participant Demographics

```{r table 1 - data cleaning}
table_1 <-dekaf %>% 
  mutate(Race = if_else(raceblack == 1, "African American", "Other", missing = NULL),
         Gender = if_else(gender == 1, "Male", "Female", missing = NULL),
         Delayed_Graft_Function = if_else(dgf == 1, "Yes", "No", missing = NULL)) %>% 
  select(Race, Gender, Delayed_Graft_Function, cardiac_death)
```

```{r table 1 - table summary}
table_1 <- table_1 %>% 
  tbl_summary(by = Delayed_Graft_Function,
              label = list(cardiac_death ~ "Donation After Cardiac Death")) %>% 
  modify_caption(caption = "**Table 1. Participant Demographics**") %>% 
  modify_header(label ~ "**Delayed Graft Function**") %>% 
   add_overall()

  
  ## gender, race, cardiac after death

table_1
```

```{r table 1 export, echo=FALSE, include=FALSE, message=FALSE}

table_1 %>%
  as_flex_table() %>%
  save_as_docx(path = "C:/Users/Lenovo/OneDrive/Documents/githubb/biostats/Biostats 2/Exports/Table_1_Week6.docx")
```

### Figure 1: Relationship between Donor Age and DGF

```{r graph summary of donor age vs DGF}
ggplot(dekaf, aes(x = DGF, y = agedonor16, fill = DGF)) +
  geom_boxplot() +
  labs(fill = "Delayed Graft Function",
       x = "",
       y = "Donor Age",
       title = "Figure 1. Distribution of Donor Age and Delayed Graft Function",
       subtitle = "Donor age refers to years beyond 16 (i.e. 17=1)") 


```

### Figure 2: Relationship between Cardiac Death and DGF

```{r graph summary of Cardiac Death vs DGF}

ggplot(dekaf, aes(fill = DGF, x = cardiac_death)) +
  geom_bar(position = "fill") +
  scale_y_continuous(labels = scales::percent) +
  labs(x = "Donation after Cardiac Death",
       y = "Percentage",
       fill = "Delayed Graft Function",
       title = "Figure 2. Proportion of Delayed Graft Function by Cardiac Death Donation Status")

```

## Results

### Table 2

```{r logistic regression model - cardiac death * donor age}

rq1 <- glm(data = dekaf,
           dgf ~ cardiac_death*agedonor16,
           family = "binomial")

summary(rq1)
```

```{r rq1 exponentiated}

tidy_rq1 <- tidy(rq1,
                 conf.int = TRUE,
                 exponentiate = TRUE)

tidy_rq1
```

```{r tidy_rq1 export, echo=FALSE, include=FALSE, message = FALSE}

tidy_rq1 %>% 
  write.csv(file = "C:/Users/Lenovo/OneDrive/Documents/githubb/biostats/Biostats 2/Exports/HW4/Table2.csv")

```

### Table 3

```{r logistic regression model - cardiac death*donor age}
rq2 <- glm(data = dekaf,
           dgf ~ agedonor16*cardiac_death,
           family = "binomial")

summary(rq2)
```

```{r rq2 exponentiated}

tidy_rq2 <- tidy(rq2,
                 conf.int = TRUE,
                 exponentiate = TRUE) %>% 
  mutate(across(where(is.numeric), ~ round(.x, 2))) %>% 
  mutate(conf_interval = paste0("(", conf.low, ", ", conf.high, ")")) %>%
  select(term, estimate, std.error, conf_interval, p.value)

tidy_rq2

```

```{r tidy_rq2 export, echo=FALSE, include=FALSE, message=FALSE}

tidy_rq2 %>% 
  write.csv(file = "C:/Users/Lenovo/OneDrive/Documents/githubb/biostats/Biostats 2/Exports/HW4/Table3.csv", row.names = FALSE)

```
