---
title: "Log Binomial Regression"
author: "Patrick Torralba"
format:
  html:
    theme: flatly
    self_contained: true
    embed-resources: true
    toc: true
    smooth-scroll: true
    number-sections: true
editor: visual
---

# Library + Load Data
```{r}
#| label: library
#| message: false
#| warning: false
#| echo: true

library(tidyverse)
library(epiR) ## Make 2x2 tables
library(gtsummary) ## convert results into table
library(broom) ## convert baseR results into tibbles

```


```{r}
#| label: load data
#| warning: false
#| message: false
#| echo: false

dekaf_dgf <- read.csv("dekaf_dgf (1).csv")

```

# Data Clean
```{r}
#| label: dekaf-dgf-df-clean

dekaf_dgf <- dekaf_dgf %>% 
  mutate(Gender = if_else(gender == 1, "Male", "Female"),
         DGF = if_else(dgf == 1, "Yes", "No")
  )



```



# 2x2 Table: Gender by DGF

Note: tbl_cross() is used to make really good 2x2 tables in html via the gtsummary package
```{r}
#| label: tbl-gender-dgf
#| tbl-cap: "2x2 Table: Gender by DGF"
#| tbl-cap-location: top


table_gender_dgf <- dekaf_dgf %>% 
  tbl_cross( 
    row = Gender,
    col = DGF) %>% 
  bold_labels()
    
table_gender_dgf
  

  

```

