---
title: "Semester Review"
author: "Patrick Torralba"
format:
  html:
    theme: flatly
    fontsize: 0.8em
    code-fold: FALSE
    code-tools: TRUE
    code-copy: TRUE
    toc: TRUE
    toc-depth: 4
    smooth-scroll: TRUE
    embed-resources: TRUE
    fig-align: center
editor: visual
---

# Set-up

## library
```{r}
#| label: library
#| message: false
#| warning: false
#| echo: true

library(tidyverse)
```


# Part 2: Key Concepts - Multiple Linear Regression

## Situation A
```{r}
#| label: fig-SBP
#| fig-cap: "SBP"
#| fig-cap-location: top
#| message: false
#| warning: false
#| echo: true

# Set seed
set.seed(42)

# define age range of 100 people in sample
age <- seq(20,80, length.out = 100)

# define SBP
sbp <- 100 + (0.6*age) + rnorm(100, mean = 0, sd = 8)

# create dataframe
df <- data.frame(age, sbp)

# create scatterplot

ggplot(df, aes(x = age, y = sbp)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Age (years)",
    y = "Systolic Blood Pressure (mmHg)",
    title = "Relationship between Systolic Blood Pressure and Age"
  )


```

## Situation B
```{r}
#| label: SBP-treatment
#| message: false
#| warning: false
#| echo: true


# Set seed
set.seed(67)

# define total sample size
sample_size <- 50


# define age range participants in both groups

age_placebo <- seq(20,80, length.out = sample_size)
  
age_treatment <- seq(20,80, length.out = sample_size)

# define sbp placebo
sbp_placebo <- 100 + (0.6*age_placebo) + rnorm(sample_size, mean = 0, sd = 8)

# define sbp treatment. Lesser value bc drug fights SBP
sbp_treatment <- 100 +(0.3*age_treatment) + rnorm(sample_size, mean = 0, sd = 8)

# combine into dataframe

df_placebo <- data.frame(Age = age, SBP = sbp_placebo, Group = "Placebo")

df_treatment <- data.frame(Age = age, SBP = sbp_treatment, Group = "treatment")

data_B <- rbind(df_placebo, df_treatment)

```


```{r}
#| label: fig-SBP-treatment
#| fig-cap: "Treatment vs SBP"
#| fig-cap-location: top
#| message: false
#| warning: false
#| echo: true

ggplot(data_B, aes(x = Age, y = SBP, color = Group)) +
  geom_point(alpha = 0.5) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Systolic Blood Pressure (SBP) vs Age by Group",
    y = "SBP (mmHg)",
    x = "Age (years)"
  )

```

