---
title: "Project 1"
author: "Patrick Torralba"
format: html
editor: visual
---

```{r}
#| label: library
#| echo: false
#| include: false
#| warning: false

library(tidyverse) # general
library(gtsummary) # create tables
library(flextable) # convert to flex table for copy-paste purposes
```

```{r}
#| label: data
#| echo: false

surgery_timing <- read.csv("Surgery Timing.csv")

```

## Data cleaning

```{r}
#| label: data cleaning

surgery_timing <- surgery_timing %>% 
  mutate(Gender = as.factor(if_else(gender == 1, "Male", "Female")),
         Race = as.factor(case_when(race == 1 ~ "Caucasian",
                          race == 2 ~ "African American",
                          race == 3 ~ "Other")),
         Asa_status = as.factor(case_when(asa_status == 1 ~ "ASA 1-2",
                                asa_status == 2 ~ "ASA 3",
                                asa_status == 3 ~ "ASA 4-6")),
         Complication = as.factor(if_else(complication == 0, "No Complication", "Complication")),
         Dow = as.factor(case_when(dow == 1 ~ "Monday",
                         dow == 2 ~ "Tuesday",
                         dow == 3 ~ "Wednesday",
                         dow == 4 ~ "Thursday",
                         dow == 5 ~ "Friday" )),
         Dow = fct_relevel(Dow, "Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
  

```

## Exploratory Data Analysis

::: {.content-hidden}

### Variables I should pull for table 1:
    -   age
    -   race
    -   gender
    -   bmi
    -   asa_status
        -   this refers to a patients physical health and combordities
    -   mort30
    
:::

### Table - Participant Demographics
```{r}
#| label: tbl-participant-demo
#| tbl-cap: "Participant Demographics"
#| tbl-cap-location: top
#| warning: false

table_1 <- surgery_timing %>% 
  tbl_summary(by = Complication,
              include = Gender:Complication,
              label = "Asa_status" ~ "ASA Status") %>% 
  add_overall() %>% 
  modify_footnote(update = label ~ "ASA: American Society of Anesthesiologists physical status classification") %>% 
  as_flex_table()

table_1
```



### Figure - Surgeries and Complications by Hour Histogram
```{r}
#| label: fig-hist-hour-comp
#| fig-cap: "Surgeries and Complications by Hour"
#| fig-cap-location: top


ggplot(surgery_timing, aes(x = hour,  fill = Complication)) +
  geom_histogram(binwidth = 1, position = "dodge") +
  scale_x_continuous(breaks = seq(0, 24, by = 4)) +
  theme_minimal() +
  theme(legend.position = "top") + 
  labs(x = "Hour (24-Hour Time)",
       y = "Surgery Count",
       fill = "Patient Status")


```

### Figure - Complications by Day of Week 
```{r}
#| label: fig-comp-dow
#| fig-cap: "Surgical In-hospital Complications by Day of Week"
#| fig-cap-location: top


ggplot(surgery_timing, aes(x = Dow, y = complication, fill = )) +
  geom_col() +
  labs(x = NULL,
       y = "Complication Count")

## I do not include the title because I screenshot the figure-cap instead

```

